### ISSUE TITLE
/sbin/sfdisk: unrecognized option '--no-tell-kernel'

### ISSUE THREAD

**Issue by ghost** [bradfitz/embiggen-disk#9]
```
sfdisk: exit status 1: /sbin/sfdisk: unrecognized option '--no-tell-kernel'

fdisk from util-linux 2.27.1

PRETTY_NAME="Ubuntu 16.04.6 LTS"
```

**Comment by bradfitz** [comment]
Your util-linux is too old.

That was added September 2016: https://github.com/karelzak/util-linux/commit/d4a90151e3b223f3c44e6148943acacd299dd168

You're running a distro from April 2016.

**Comment by bradfitz** [comment]
(Also this is a dup of #6 which is still open.)
